[project]
name = "lecture-01-a-simple-ai-agent-using-openai-agents-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.7.1.1",
    "openai-agents>=0.2.8",
    "python-decouple>=3.8",
]
